name: SkinRestorer
version: 12-Bh-Alpa.v1.23mc
author: voidles02
main: com.KDI.skinrestorer.SkinRestorerPlugin
api-version: '1.21'
description: Restores and manages player skins in offline and online mode.
commands:
  skin:
    description: Manage player skins.
    usage: /skin <set|url|clear|update|random>
    aliases: [skins]
permissions:
  skinsrestorer.command.set:
    default: true
  skinsrestorer.command.url:
    default: true
  skinsrestorer.command.clear:
    default: true
  skinsrestorer.command.update:
    default: true
  skinsrestorer.command.random:
    default: true
  skinsrestorer.admin:
    default: op